title: Neural Computation and Behavior
description: Neural computation and behavior lab studying acoustic communication in insects with computational tools.
author: Jan Clemens
lang: en
timezone: Europe/Berlin
url: "https://janclemenslab.org"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass
